// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_D1oolYgXSrqSe7wyYnNi5eD3lUeOQu0',
    appId: '1:261152586063:web:04ca70334105edd467ed3a',
    messagingSenderId: '261152586063',
    projectId: 'word-pracise-cz-en',
    authDomain: 'word-pracise-cz-en.firebaseapp.com',
    storageBucket: 'word-pracise-cz-en.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0FmlxZkXVWl6sH5EHSz7nkBJ9X1rTND4',
    appId: '1:261152586063:android:c40ffbcfeb30f7b067ed3a',
    messagingSenderId: '261152586063',
    projectId: 'word-pracise-cz-en',
    storageBucket: 'word-pracise-cz-en.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYAiOyB8srRnDHddyvxmiKOFZcF5Sjg4o',
    appId: '1:261152586063:ios:b7409f9ec2cd647967ed3a',
    messagingSenderId: '261152586063',
    projectId: 'word-pracise-cz-en',
    storageBucket: 'word-pracise-cz-en.appspot.com',
    iosBundleId: 'com.google.firebase.presents.wordPractiseFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYAiOyB8srRnDHddyvxmiKOFZcF5Sjg4o',
    appId: '1:261152586063:ios:7ff44388069ffacc67ed3a',
    messagingSenderId: '261152586063',
    projectId: 'word-pracise-cz-en',
    storageBucket: 'word-pracise-cz-en.appspot.com',
    iosBundleId: 'com.google.firebase.presents.wordPractiseFirebase.RunnerTests',
  );
}
